services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sqlserver-container
    restart: always
    ports:
      - "1435:1433"
    env_file:
      - .env
    environment:
      SA_PASSWORD: "${PROD_DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - mvc-network
    healthcheck:
      test: ["CMD-SHELL", "dotnet sqlcmd -S localhost -U ${PROD_DB_USER} -P ${PROD_DB_PASSWORD}-Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  mvc-movie:
    image: "vuyisile28/mvc-movie:wv2"
    container_name: mvc-movie-container
    restart: always
    ports:
      - "8080:80"
    depends_on:
      sqlserver:
        condition: service_started
    networks:
      - mvc-network
    env_file:
      - .env

networks:
  mvc-network:

volumes:
  sqlserver-data:
