apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-movie
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels:
      app: mvc-movie
  template:
    metadata:
      labels:
        app: mvc-movie
    spec:
      containers:
      - name: mvc-movie
        image: vuyisile28/mvc-movie:wv2
        ports:
          - containerPort: 80
        env:
          - name: PROD_DB_SERVER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PROD_DB_SERVER
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_NAME
          - name: PROD_DB_USER
            valueFrom:
              secretKeyRef:
                name: sa-secret
                key: DB_USER
          - name: PROD_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sa-secret
                key: DB_PASSWORD          


---
apiVersion: v1
kind: Service
metadata:
  name: mvc-movie-service
spec:
  type: NodePort
  selector:
    app: mvc-movie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008  # Expose app on Minikube at port 30008
