apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: mvc-movie-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sa-secret
              key: DB_PASSWORD
        resources:  # ADD THIS SECTION
          requests:
            cpu: "2"  # Minimum 2 CPU cores
            memory: "4Gi"  # Minimum 4GB RAM
          limits:
            cpu: "4"  # Maximum 4 CPU cores
            memory: "8Gi"  # Maximum 8GB RAM

        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql
        

      volumes:
      - name: sqlserver-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
