name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

  docker-build-push:
    name: Build & Push Docker Image
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t vuyisile28/mvc-movie:wv2 -f Dockerfile .

      - name: Push Docker Image to Docker Hub
        run: docker push vuyisile28/mvc-movie:wv2

  deploy:
    name: Deploy to Minikube
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Minikube
        run: |
          minikube start --cpus=4 --memory=8192
          kubectl config use-context minikube

      - name: Apply Kubernetes Namespace
        run: kubectl apply -f namespace.yaml

      - name: Create Secret in Kubernetes
        run: |
          kubectl create secret generic sqlserver-secret \
            --namespace=mvc-movie-namespace \
            --from-literal=PROD_DB_USER=sa \
            --from-literal=PROD_DB_PASSWORD=${{ secrets.MVC_MOVIE_DB_PASSWORD }}
      
      - name: Apply ConfigMap
        run: kubectl apply -f configmap.yaml --namespace=mvc-movie-namespace

      - name: Deploy SQL Server
        run: kubectl apply -f sqlserver-deployment.yaml --namespace=mvc-movie-namespace

      - name: Wait for SQL Server to be Ready
        run: |
          kubectl rollout status deployment/sqlserver --namespace=mvc-movie-namespace --timeout=300s 
          sleep 30  # Extra wait time just to be sure
      
      - name: Deploy MVC Movie App
        run: kubectl apply -f mvc-movie-deployment.yaml --namespace=mvc-movie-namespace

      - name: Wait for MVC Movie App to be Ready
        run: kubectl rollout status deployment/mvc-movie --namespace=mvc-movie-namespace --timeout=300s